name: Build
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # checkout
    - uses: actions/checkout@v2
    # compile
    - run: ./compile.sh
    # upload to build artifact
    - uses: actions/upload-artifact@v2
      with:
        path: disk.qcow2
